### ISSUE TITLE
Add 404 page with responsiveness

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#1]

**Comment by QaisarMoin** [comment]
please assign this issue to me

**Comment by Azhar221** [comment]
Hello @Aditya-jambhale, I would like to work on this issue. Assign me

**Comment by ReshmaZore** [comment]
Hello maintainers , I want to work on this issue

**Comment by devRoshan-25** [comment]
hello maintainer , i want to work on this issue

**Comment by TickleFuse09** [comment]
Hey maintainers, i want to solve this issue.

**Comment by Aditya-jambhale** [comment]
> Hello maintainers , I want to work on this issue

Go for it complete your pr within 24hrs asap
