### ISSUE TITLE
Navbar is not visible fix it 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#17]
![image](https://github.com/user-attachments/assets/57bd3f21-c5a7-4164-be5a-203a86a90563)
after fixing add a Screenshot or video of the output

**Comment by stg2209** [comment]
could i be assigned the issue ?

**Comment by Mehnaz2004** [comment]
Hey maintainer, assign this to me i would like to work on it.

**Comment by Mehnaz2004** [comment]
Hey maintainer can i be assigned this issue

**Comment by stg2209** [comment]
Have opened a PR ( #19) regarding it. Please review it.

**Comment by TechMe103** [comment]
hey maintainers i want to work on this issue

**Comment by Parth-code286** [comment]
Hey maintainer , i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey maintainer can i be assigned this issue

go for it
