### ISSUE TITLE
Fix the logo add some new logo which relates to the tourism ensure the responsiveness 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#18]
![Screenshot 2024-10-06 030400](https://github.com/user-attachments/assets/57ef5e4a-658b-4973-b5a3-d16caaa712ae)

upload your output image

**Comment by Aditya-jambhale** [comment]
> ![Screenshot 2024-10-06 030400](https://private-user-images.githubusercontent.com/145918039/373909069-57ef5e4a-658b-4973-b5a3-d16caaa712ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNjQzNzcsIm5iZiI6MTcyODE2NDA3NywicGF0aCI6Ii8xNDU5MTgwMzkvMzczOTA5MDY5LTU3ZWY1ZTRhLTY1OGItNDk3My1iNWEzLWQxNmNhYWE3MTJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQyMTM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTYyYzdjZWVmMWRmZmI0NjAwZWMwZGM1ZGE2MmVmNTc1MWU3OTgwOGNkM2RmYzY3NDViNjIxN2UxOWM4MmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q9FsivNBYMkb0t499R0_mMFQ9tkYGZffb74_dp10SNs)

upload your output image

**Comment by DanonymousCoder** [comment]
Hi, can I work on this?

**Comment by TechMe103** [comment]
hey maintainers , i would like to work on this issue. plz assign to me this issue

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by Aditya-jambhale** [comment]
> Hello Maintainer , Can I work on this issue?

Complete it asap

**Comment by Vikas3100** [comment]
Please assign me this issue

**Comment by YashBawari18** [comment]
Hello Maintainer , Can I work on this issue?
