### ISSUE TITLE
Create a signup and login page

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#2]
![Screenshot 2024-10-04 194305](https://github.com/user-attachments/assets/2c5b79f6-5ec6-42f0-86c0-053e793b60fc)

**Comment by Parth-code286** [comment]
Hey maintainer i want to work on this issue

**Comment by tghosh294** [comment]
Hello maintainer, I would like to work on this issue. Assign me

**Comment by ReshmaZore** [comment]
Hello maintainer , I would like to work on this issue

**Comment by TickleFuse09** [comment]
Hey maintainers, I'd like to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hello maintainer, I would like to work on this issue. Assign me

Go for it , try to complete in 24 hrs asap

**Comment by Aditya-jambhale** [comment]
Issue is solved and hence closed
