### ISSUE TITLE
Add a feature to the contact us page when the user clicks on that phone no,email,button it should be copied to Clipboard 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#26]
![Screenshot 2024-10-06 225934](https://github.com/user-attachments/assets/fc348490-3a6d-4e15-a765-3035dbe949b9)
the buttons here which are on the left side they should be copied to clipboard whenever the user clicks on them

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.

**Comment by samusahatpure** [comment]
Hello sir,  I would like to work on it, can you please assign this to me?

**Comment by Abhinav-gh** [comment]
Hello! I am actively participating to HacktoberFest 2024. Could you please assign this issue to me?

**Comment by Aditya-jambhale** [comment]
> Hello maintainers, I want to work on this issue.

Go for it , complete it asap and add a video while raising a pr

**Comment by TechMe103** [comment]
hey maintainers , i would like to work on this issue... plz can u assign me to this one
