### ISSUE TITLE
Add Responsive Footer to all tabs

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#3]

**Comment by Parth-code286** [comment]
Hey maintainer i want to work on this issue

**Comment by TechMe103** [comment]
hello maintainers i would like to work on this issue

**Comment by Shreyashjadhav1001** [comment]
Hey Maintainer, i want to work on this issue

**Comment by TickleFuse09** [comment]
Hey maintainers, I'd like to solve this issue

**Comment by SanjanaSaw** [comment]
Hey maintainers, I'd like to solve this issue

**Comment by Shreyashjadhav1001** [comment]
Hey maintainers, I  want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hey Maintainer, i want to work on this issue

Go for it try to complete it asap

**Comment by nupurnigudkar9404** [comment]
Hey Maintainers, I want to work on this issue
