### ISSUE TITLE
Add a responsive contact us page with animations 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#4]

**Comment by QaisarMoin** [comment]
please can you assign this issue to me ?

**Comment by Mehnaz2004** [comment]
Hello maintainer, I would like to work on this issue. Assign me

**Comment by Aditya-jambhale** [comment]
> Hello maintainer, I would like to work on this issue. Assign me

Go for it , try to complete it asap

**Comment by nupurnigudkar9404** [comment]
Hey maintainers, I want to work on this issue

**Comment by TechMe103** [comment]
hey maintainers , i want to work on this issue

**Comment by YashBawari18** [comment]
Hello maintainers, I would like to work on this issue, Kindly Assign me...

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.
