### ISSUE TITLE
Make the Navbar responsive that toggles vertically on smaller screens (i.e mobile view) .

### ISSUE THREAD

**Issue by BhoomiSingh13** [CSI-DMCE-2024/Tourism-Blog-Hacktoberfest-2024#8]
I want the navbar to be horizontal on larger screens and , when resized to smaller screens i.e. mobile view , it should collapse into a menu and appear vertically . Upon clicking the button, the menu should toggle open , displaying the items vertically , when clicked on the menu again it should close .

Here's an Example  ,
![Toggle Navbar](https://github.com/user-attachments/assets/b9ce83f5-70bc-4006-8dee-b102764708b6)

**Comment by FSfarhaan** [comment]
Hey maintainer, kindly assign this issue to me

**Comment by tghosh294** [comment]
Hello Maintainers, I want to work upon this issue.

**Comment by BhoomiSingh13** [comment]
> Hey maintainer, kindly assign this issue to me

Go for it complete it asap

**Comment by nupurnigudkar9404** [comment]
Hey maintainers, i want to work on this issue

**Comment by Junkie-source** [comment]
hey maintainers, i want to work on this issue

**Comment by TechMe103** [comment]
hey maintainers , can u assign to me this issue

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.

**Comment by YashBawari18** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Aditya-jambhale** [comment]
> Hey maintainers, i want to work on this issue

Go for it and complete it asap

**Comment by Aditya-jambhale** [comment]
> hello maintainers I want to work on this issue

Go for it and try to complete it asap

**Comment by AdK819** [comment]
Hello Maintainer! Aditi here 
May I work on this issue?

**Comment by Aditya-jambhale** [comment]
> hey maintainers, i want to work on this issue

go for it and try to complete it asap

**Comment by nupurnigudkar9404** [comment]
hello maintainer i want to work on this issue

**Comment by Aditya-jambhale** [comment]
> hello maintainer i want to work on this issue

go for it
